FROM ubuntu:24.04

# Install necessary packages
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install -y wget bzip2 make unzip cppcheck git

# Create a non-root user named "lintu"
RUN useradd -rm -d /home/lintu -s /bin/bash -g root -G sudo \
    -u 51 lintu

USER lintu

WORKDIR /home/lintu