FROM ubuntu:24.04

# Install necessary packages
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install -y wget bzip2 make unzip cppcheck sudo git

# Create a non-root user named "lintu"
RUN useradd -rm \
    -d /home/lintu \
    -s /bin/bash    \
    -u 51 lintu     \
    && echo "lintu:lintu" | chpasswd    \
    && adduser lintu sudo

USER lintu

WORKDIR /home/lintu