name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: ibrahimoladepo/stm32f401xx-gcc-10.3
        options: --user root

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make GCC_PATH=~/dev/gcc-arm-none-eabi-10.3-2021.10/bin